import './globals.css'
import { Inter } from 'next/font/google'
import AuthProvider from './AuthProvider'
import NavMenu from './NavMenu'
import { getServerSession } from 'next-auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'MySpace - Next',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const session = await getServerSession()

	return (
		<AuthProvider>
			<html lang='en'>
				<body className={inter.className}>
					{/* @ts-ignore */}
					<NavMenu />
					{children}
				</body>
			</html>
		</AuthProvider>
	)
}
